import { type NextPage } from 'next';
import Head from 'next/head';
import styles from './index.module.css';

import { api } from '../utils/api';

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' });

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.headSection}>
          <h2 className={styles.header}>My Shopping List</h2>
        </div>
        <div className={styles.buttonArea}>
          <button className={styles.button} type="button">
            Test Button
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
